### ISSUE TITLE
XL rate incorrectness

### ISSUE THREAD

**Issue by avrland** [STMicroelectronics/lsm6dso32-pid#4]
Previewing lsm6dso32 datasheet (DocID032891 Rev 1) I found out that lowest XL rate is 1.6Hz, not 6,5Hz. 

Lines below should be corrected as they are misleading:
https://github.com/STMicroelectronics/lsm6dso32-pid/blob/49919136f3011d7243906dd25e69df90501063ed/lsm6dso32_reg.h#L2680
https://github.com/STMicroelectronics/lsm6dso32-pid/blob/49919136f3011d7243906dd25e69df90501063ed/lsm6dso32_reg.h#L2702

**Comment by avrland** [comment]
Related PR: https://github.com/STMicroelectronics/lsm6dso32-pid/pull/7

**Comment by avisconti** [comment]
Fixed by 3bf252e
